USE SuaChuaThietBi
GO

CREATE TABLE PhieuDeNghi(
	MaForm VARCHAR(30) UNIQUE NOT NULL,
	TenForm NVARCHAR(300) NOT NULL,
	TenFile NVARCHAR(300) NOT NULL,
	FileCode VARBINARY(MAX) NOT NULL,
	NgayCapNhat DATE NOT NULL
)
